[package]
name = "ssf"
description = "Structurally-typed strict functional core language"
version = "0.1.0"
license = "MIT"
authors = ["Yota Toyama <raviqqe@gmail.com>"]
edition = "2018"

[dependencies]
petgraph = "0.5"
